[package]
name = "clap_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo = "0.87.1"
clap = "4.5.37"
features = "0.10.0"
